import "server-only";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

export function generateNoteFilename(
  createdAt: Date,
  title: string,
  usedFilenames: Set<string>,
): string {
  const date = createdAt.toISOString().slice(0, 10);
  const slug = slugify(title) || "untitled";
  const base = `${date}-${slug}`;

  let candidate = `${base}.md`;
  if (!usedFilenames.has(candidate)) {
    usedFilenames.add(candidate);
    return candidate;
  }

  let counter = 2;
  while (true) {
    candidate = `${base}-${counter}.md`;
    if (!usedFilenames.has(candidate)) {
      usedFilenames.add(candidate);
      return candidate;
    }
    counter++;
  }
}

export const PURPOSE_FOLDER_NAMES: Record<string, string> = {
  note: "General",
  meeting_note: "Meeting Notes",
  project_brief: "Project Briefs",
  reading_note: "Reading Notes",
};

export function purposeFolderName(purpose: string): string {
  return PURPOSE_FOLDER_NAMES[purpose] ?? purpose;
}

export function generateNoteFrontmatter(note: {
  id: string;
  title: string;
  purpose: string;
  project_name: string | null;
  created_at: Date;
  updated_at: Date;
  body_markdown: string;
}): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push("# Generated by Atlas. Edits to this file will be overwritten on next sync.");
  lines.push(`atlas_id: ${note.id}`);
  lines.push(`title: ${JSON.stringify(note.title)}`);
  lines.push(`purpose: ${note.purpose}`);
  if (note.project_name) {
    lines.push(`project_name: ${JSON.stringify(note.project_name)}`);
  }
  lines.push(`created_at: ${note.created_at.toISOString()}`);
  lines.push(`updated_at: ${note.updated_at.toISOString()}`);
  lines.push("---");
  lines.push("");
  lines.push(note.body_markdown);
  return lines.join("\n");
}
