import "server-only";
import type { ColumnConfig, ColumnType, SingleSelectOption } from "./types";
import { formatCellValueForCsv, deserializeCellValue } from "./validators";
import { isMultiSelectValue } from "./types";
import { isFormulaError, FORMULA_ERROR_KEY } from "./formula-shared";

interface ExportColumn {
  id: string;
  name: string;
  type: ColumnType;
  position: number;
  config: ColumnConfig;
  aggregation?: string | null;
  width: number;
}

interface ExportCell {
  column_id: string;
  value: unknown;
}

interface ExportRow {
  id: string;
  cells: ExportCell[];
}

interface ExportTable {
  id: string;
  name: string;
  description?: string | null;
  created_at: Date;
  updated_at: Date;
  columns: ExportColumn[];
  rows: ExportRow[];
  project?: { title: string } | null;
  folder?: { name: string } | null;
}

export function exportTableCsv(table: ExportTable): string {
  const cols = [...table.columns].sort((a, b) => a.position - b.position);
  const header = cols.map((c) => csvEscape(c.name)).join(",");

  const dataRows = table.rows.map((row) => {
    return cols
      .map((col) => {
        const cell = row.cells.find((c) => c.column_id === col.id);
        const rawVal = cell?.value ?? null;

        // Formula columns: the cell already carries the computed value (injected by the server)
        if (col.type === "formula") {
          if (isFormulaError(rawVal)) return csvEscape("#ERROR");
          if (rawVal === null || rawVal === undefined) return "";
          return csvEscape(String(rawVal));
        }

        if (col.type === "multi_select") {
          const deserialized = deserializeCellValue(col.type, rawVal);
          const options = (col.config.options ?? []) as SingleSelectOption[];
          return csvEscape(formatCellValueForCsv(col.type, deserialized, options));
        }

        const deserialized = deserializeCellValue(col.type, rawVal);
        return csvEscape(formatCellValueForCsv(col.type, deserialized));
      })
      .join(",");
  });

  return [header, ...dataRows].join("\n");
}

export function exportTableJson(table: ExportTable): string {
  const cols = [...table.columns].sort((a, b) => a.position - b.position);

  const schema = {
    comment: "Generated by Atlas. Edits to this file will be overwritten on next sync.",
    table: {
      id: table.id,
      name: table.name,
      description: table.description ?? null,
      project: table.project?.title ?? null,
      folder: table.folder?.name ?? null,
      created_at: table.created_at.toISOString(),
      updated_at: table.updated_at.toISOString(),
    },
    columns: cols.map((col) => {
      if (col.type === "formula") {
        return {
          id: col.id,
          name: col.name,
          type: col.type,
          position: col.position,
          config: col.config,
          aggregation: col.aggregation ?? null,
          width: col.width,
          formula: {
            expression: (col.config as { expression?: string }).expression ?? "",
            return_type: (col.config as { return_type?: string }).return_type ?? "text",
          },
        };
      }
      return {
        id: col.id,
        name: col.name,
        type: col.type,
        position: col.position,
        config: col.config,
        aggregation: col.aggregation ?? null,
        width: col.width,
      };
    }),
    rows: table.rows.map((row) => ({
      id: row.id,
      cells: cols.map((col) => {
        const cell = row.cells.find((c) => c.column_id === col.id);
        const rawVal = cell?.value ?? null;
        // Formula cells: store computed value (errors as null)
        if (col.type === "formula") {
          if (isFormulaError(rawVal))
            return {
              column_id: col.id,
              value: null,
              [FORMULA_ERROR_KEY]: (rawVal as unknown as Record<string, string>)[FORMULA_ERROR_KEY],
            };
          return { column_id: col.id, value: rawVal };
        }
        if (col.type === "multi_select") {
          if (isMultiSelectValue(rawVal)) {
            return { column_id: col.id, option_ids: rawVal.option_ids };
          }
          return { column_id: col.id, option_ids: [] };
        }
        return { column_id: col.id, value: rawVal };
      }),
    })),
    row_count: table.rows.length,
  };

  return JSON.stringify(schema, null, 2);
}

function csvEscape(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}
