import "server-only";
import type { ColumnConfig, ColumnType } from "./types";
import { formatCellValueForCsv, deserializeCellValue } from "./validators";

interface ExportColumn {
  id: string;
  name: string;
  type: ColumnType;
  position: number;
  config: ColumnConfig;
  aggregation?: string | null;
  width: number;
}

interface ExportCell {
  column_id: string;
  value: unknown;
}

interface ExportRow {
  id: string;
  cells: ExportCell[];
}

interface ExportTable {
  id: string;
  name: string;
  description?: string | null;
  created_at: Date;
  updated_at: Date;
  columns: ExportColumn[];
  rows: ExportRow[];
  project?: { title: string } | null;
  folder?: { name: string } | null;
}

export function exportTableCsv(table: ExportTable): string {
  const cols = [...table.columns].sort((a, b) => a.position - b.position);
  const header = cols.map((c) => csvEscape(c.name)).join(",");

  const dataRows = table.rows.map((row) => {
    return cols.map((col) => {
      const cell = row.cells.find((c) => c.column_id === col.id);
      const rawVal = cell?.value ?? null;
      const deserialized = deserializeCellValue(col.type, rawVal);
      return csvEscape(formatCellValueForCsv(col.type, deserialized));
    }).join(",");
  });

  return [header, ...dataRows].join("\n");
}

export function exportTableJson(table: ExportTable): string {
  const cols = [...table.columns].sort((a, b) => a.position - b.position);

  const schema = {
    comment: "Generated by Atlas. Edits to this file will be overwritten on next sync.",
    table: {
      id: table.id,
      name: table.name,
      description: table.description ?? null,
      project: table.project?.title ?? null,
      folder: table.folder?.name ?? null,
      created_at: table.created_at.toISOString(),
      updated_at: table.updated_at.toISOString(),
    },
    columns: cols.map((col) => ({
      id: col.id,
      name: col.name,
      type: col.type,
      position: col.position,
      config: col.config,
      aggregation: col.aggregation ?? null,
      width: col.width,
    })),
    row_count: table.rows.length,
  };

  return JSON.stringify(schema, null, 2);
}

function csvEscape(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}
