/* Reading-mode sample data — long-form journal entries */
window.READING_DATA = {
  collections: [
    { id: "all",    label: "All entries", color: "oklch(70% 0.02 250)", count: 412 },
    { id: "today",  label: "Today",       color: "oklch(72% 0.16 30)",  count: 2 },
    { id: "starred",label: "Starred",     color: "oklch(78% 0.14 75)",  count: 27 },
    { id: "drafts", label: "Drafts",      color: "oklch(70% 0.02 250)", count: 4 },
  ],
  notebooks: [
    { id: "journal",  label: "Journal",       color: "oklch(70% 0.16 240)", count: 286 },
    { id: "field",    label: "Field notes",   color: "oklch(72% 0.16 150)", count: 64 },
    { id: "reading",  label: "Reading log",   color: "oklch(72% 0.16 30)",  count: 38 },
    { id: "morning",  label: "Morning pages", color: "oklch(78% 0.14 75)",  count: 24 },
  ],
  tags: [
    { id: "rituals",  label: "rituals",  count: 18 },
    { id: "fog",      label: "fog",      count: 6 },
    { id: "running",  label: "running",  count: 31 },
    { id: "work",     label: "work",     count: 92 },
    { id: "kyoto",    label: "kyoto",    count: 11 },
  ],
  entries: [
    {
      id: "e1",
      dayKey: "2025-10-15",
      dayLabel: "Wed, Oct 15 2025",
      dayRel: "Today",
      time: "06:42",
      title: "On the discipline of beginning before the day asks anything of you",
      excerpt: "The light at the kitchen window is the same color as the steam off the kettle, and that is the only news I require this morning…",
      words: 824,
      read: 4,
      location: "Bernal Heights",
      notebook: "Journal",
      pinned: true,
      tags: ["rituals", "morning", "fog"],
      weather: { temp: "11°C", cond: "Marine layer", location: "San Francisco, CA" },
      body: [
        { type: "p", text: "The light at the kitchen window is the same color as the steam off the kettle, and that is the only news I require this morning. I have been trying — for what feels like a long stretch of seasons now — to begin the day before it begins making demands of me. The trick is not in waking earlier. The trick is in refusing to <em>negotiate</em>." },
        { type: "p", text: "I open the notebook. I do not check the phone. The room is cold enough to be evidence of the world but not so cold that it argues with me. There is a small pleasure in being awake while the city is still bargaining with itself about whether to begin." },
        { type: "h2", text: "What the page is for" },
        { type: "p", text: "The page is not for confession and it is not for resolution. It is closer to a bench at the edge of a path: a place where you sit so that the walking, when it resumes, is yours. I write in fragments because the morning is in fragments. The cohesion comes later, or it does not come, and either way the bench was useful." },
        { type: "quote", text: "We do not write in order to be understood; we write in order to understand.", cite: "C. Day-Lewis, paraphrased from memory" },
        { type: "p", text: "There is a temptation to make the morning <a href=\"#\" className=\"r-tag-link\">#productive</a> — to crowd it with little victories so that the rest of the day cannot accuse it of softness. I have stopped doing this. The morning's job is not to win the day in advance. Its job is to put a clean surface down under it." },
        { type: "h3", text: "Three small observations" },
        { type: "ul", items: [
          "The fog has not moved in an hour. It is not weather; it is furniture.",
          "The cat has decided the rug is acceptable. This is a concession; do not press it.",
          "There is a draft under the door I have ignored for two winters. It is not unkind to live with small inefficiencies.",
        ] },
        { type: "p", text: "By eight the light will be ordinary again, and I will have a list of <a href=\"#\" className=\"r-tag-link\">#work</a> things that need answers, and the answers will arrive on their own clock. Until then there is the page, the kettle, and the discipline — slight, almost embarrassed — of being the first room in the house with the lamp on." },
        { type: "hr" },
        { type: "p", text: "Tomorrow I will try to write about <code>cold-start</code> rituals more carefully. There is a difference between ritual and habit that I have not yet found a clean sentence for." },
      ],
    },
    {
      id: "e2",
      dayKey: "2025-10-15",
      dayLabel: "Wed, Oct 15 2025",
      dayRel: "Today",
      time: "22:08",
      title: "Notes from a long run, a slower one than I intended",
      excerpt: "Crissy Field, the wind off the bay. Twelve kilometers. The legs were honest tonight in a way they have not been all week…",
      words: 412,
      read: 2,
      location: "Crissy Field",
      notebook: "Field notes",
      pinned: false,
      tags: ["running", "evening"],
      body: [
        { type: "p", text: "Crissy Field, the wind off the bay. Twelve kilometers. The legs were honest tonight in a way they have not been all week. There is a kind of running where you are negotiating with the body the whole time and a kind where the body has already conceded — tonight was the second kind, and it was a relief." },
        { type: "h3", text: "Splits" },
        { type: "p", text: "<code>5:42 · 5:38 · 5:31 · 5:29 · 5:24 · 5:22 · 5:21 · 5:18 · 5:17 · 5:14 · 5:11 · 4:58</code>" },
      ],
    },
    {
      id: "e3",
      dayKey: "2025-10-14",
      dayLabel: "Tue, Oct 14 2025",
      dayRel: "Yesterday",
      time: "07:15",
      title: "An argument I keep having with myself about meetings",
      excerpt: "If a meeting could have been a document, I am not sure why we held the meeting. But if a document could have been a meeting…",
      words: 612,
      read: 3,
      location: "Bernal Heights",
      notebook: "Journal",
      pinned: false,
      tags: ["work", "rituals"],
      body: [{ type: "p", text: "Most meetings, in retrospect, were arguments held aloud about things that had already been decided in writing somewhere else." }],
    },
    {
      id: "e4",
      dayKey: "2025-10-13",
      dayLabel: "Mon, Oct 13 2025",
      dayRel: "Monday",
      time: "21:42",
      title: "Reading log — finished the Calvino, started the Ishiguro",
      excerpt: "Calvino is a writer who builds rooms inside rooms; you do not finish him so much as walk further in…",
      words: 308,
      read: 2,
      location: "Bernal Heights",
      notebook: "Reading log",
      pinned: false,
      tags: ["reading"],
      body: [{ type: "p", text: "Calvino is a writer who builds rooms inside rooms; you do not finish him so much as walk further in." }],
    },
    {
      id: "e5",
      dayKey: "2025-10-11",
      dayLabel: "Sat, Oct 11 2025",
      dayRel: "Last weekend",
      time: "15:24",
      title: "Kyoto, late afternoon, the stone garden empty",
      excerpt: "The thing nobody tells you about the rock garden at Ryōan-ji is that the gravel is the loud part…",
      words: 740,
      read: 4,
      location: "Kyoto",
      notebook: "Field notes",
      pinned: true,
      tags: ["kyoto", "travel"],
      body: [{ type: "p", text: "The thing nobody tells you about the rock garden at Ryōan-ji is that the gravel is the loud part." }],
    },
  ],
};
