-- AlterTable
ALTER TABLE "AICallLog" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Attachment" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "AuditLog" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "DriveConfig" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "IntegrationToken" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "RateLimitTracker" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SyncState" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
